# Totori - User Acceptance Testing Workbench
# http://totori.org/ - MIT License

#
# Configuration
#
config:
  
  watir:
    
    # Choose the browser used for the automated behavior testing
    # Available values: ie, firefox, chrome, safari, celerity
    browser: ie
    
    # Determines the speed at which the browser tests occur
    # Available values: slow, normal, fast
    # WARNING: Only works for the IE browser - should be commented else
    speed: fast
    
    # Maximizes the browser window at launch
    # Available values: true, false
    maximize: false
    
    # Brings the browser to front at launch
    # Available values: true, false
    # WARNING: Only works for the IE browser - should be commented else
    bring_to_front: true
    
  report:
    
    # Directory of the generated reports
    # (i.e. reports)
    dir: reports
    
    # Reports's embedded screenshots
    screenshots:
      
      # Time screenshots should be taken at
      # Available values:
      # - never
      # - each scenario
      # - each failed scenario
      # - each step
      # - each failed step
      after: each failed step
      
      # Directory of the generated reports' screenshots
      # (i.e. screens)
      dir: screens
